info:
  app:
    name: thumbnail-service
    description: Produces thumbnails for books, movies, newspapers, etc.

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8046

spring:  

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/